### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by chuangkezhou** [ibrahimjad/tangent_planner#2]
oh,i try to run the package a night,but i can't .I want to know how to run in my workspace ,please give me more tips or information,thank you.

**Comment by chuangkezhou** [comment]
you didn't update a launch file,

**Comment by ibrahimjad** [comment]
The package has been tested to work with ROS melodic. Not sure about other ROS versions. 

Here I am using a turtlebot_3, so you need to install that and then edit the move_base launch file to use the tanget_planner instead as written in the installation section of the README.md

Hope this helps

**Comment by chuangkezhou** [comment]
Thank you.I got it.
